spring:
    application:
        name: "customer-service"
    datasource:
        username: root
        password: root123
        url: jdbc:mysql://localhost:3306/customer_db
        driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
        active:
            - "UAT"
springdoc:
    api-docs:
        enabled: false
logging:
    file:
        name: logs/customer.logs
#custome file properties
build:
    version: "2.0"
customers:
    message: "Welcome to MSEDCL bank customer created REST API"
    contactDetails:
        name: "Veerti"
        email: "veerti@mahadiscom.in"
    onCallSupport:
        - 123457890
        - 987654125
#below content is off application.properties file, this file was rename to application.yaml
#spring.application.name=02_CustomerService
#spring.datasource.username=root
#spring.datasource.password=root123
#spring.datasource.url=jdbc:mysql://localhost:3306/customer_db
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#logging.file.name=logs/customers.log
#springdoc.swagger-ui.enabled=false
